"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
import os
from corsheaders.defaults import default_headers

# =====================
# BASE DIR
# =====================
BASE_DIR = Path(__file__).resolve().parent.parent


# =====================
# SECURITY
# =====================
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-change-me-in-production"
)

DEBUG = True

ALLOWED_HOSTS = ["*"]


# =====================
# APPLICATIONS
# =====================
INSTALLED_APPS = [
    # CORS (MUST BE FIRST APP)
    "corsheaders",

    # Django core
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party
    "rest_framework",
    "rest_framework_simplejwt",
    "drf_yasg",
    "graphene_django",

    # Local apps
    "users",
    "emails.apps.EmailsConfig",
    "scanner.apps.ScannerConfig",
    "backend.common",
    
    # future additional features
    # "realtime",
]


# =====================
# MIDDLEWARE
# =====================
MIDDLEWARE = [
    # CORS (MUST BE FIRST MIDDLEWARE)
    "corsheaders.middleware.CorsMiddleware",

    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",

    "django.contrib.auth.middleware.AuthenticationMiddleware",

    # Custom gateway logic
    "middleware.security_gateway.SecurityGatewayMiddleware",
    "middleware.api_key_gate.ApiKeyGateMiddleware",
    "middleware.intelligent_router.IntelligentServiceRouterMiddleware",
    "middleware.response_logger.ResponseLoggingMiddleware",

    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# =====================
# URL / TEMPLATES
# =====================
ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# =====================
# WSGI (HTTP ONLY)
# =====================
WSGI_APPLICATION = "backend.wsgi.application"


# =====================
# DATABASE
# =====================
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB", "postgres"),
        "USER": os.environ.get("POSTGRES_USER", "postgres"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "postgres"),
        "HOST": os.environ.get("POSTGRES_HOST", "db"),
        "PORT": os.environ.get("POSTGRES_PORT", 5432),
    }
}


# =====================
# AUTH / PASSWORDS
# =====================
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

AUTH_USER_MODEL = "users.User"


# =====================
# INTERNATIONALIZATION
# =====================
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# =====================
# STATIC FILES
# =====================
STATIC_URL = "static/"


# =====================
# DEFAULT PK
# =====================
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# =====================
# DRF / JWT
# =====================
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}


LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/login/"


# =====================
# GRAPHQL (Graphene)
# =====================
GRAPHENE = {
    "SCHEMA": "backend.schema.schema",
    "MIDDLEWARE": [
        "middleware.graphql_middleware.GraphQLMiddleware",
    ],
}


# =====================
# CORS CONFIGURATION
# =====================

# DEV MODE (browser access allowed from anywhere)
CORS_ALLOW_ALL_ORIGINS = True

# Allow cookies / Authorization headers
CORS_ALLOW_CREDENTIALS = True

# Explicitly allow JWT Authorization header
CORS_ALLOW_HEADERS = list(default_headers) + [
    "authorization",
]


# =====================
# LOGGING
# =====================
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "formatters": {
        "json": {
            "()": "pythonjsonlogger.jsonlogger.JsonFormatter",
            "fmt": "%(asctime)s %(levelname)s %(name)s %(message)s",
        }
    },

    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "json",
        }
    },

    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },

    "loggers": {
        "gateway_logger": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        }
    },
}

